#!/bin/bash

# this script is part of an autoInstall archive which installs SetupHelper
#	previous versions of blindInstall also installed GuiMods but has since been removed
# 	since PackageManager will install all package archives found on the SD/USB media so 
#	the result is the same (or actually better)
#
# the archive makes use of the Venus OS update-data.sh script
# archives named "venus-data.tar.gz" are unpacked during boot
# then for this archive, Venus must be rebooted, causing rcS.local to run,
# which calls blindInstall as a background task.
#
# Package install scripts will append to rcS.local, so it must be moved out of the way
# BEFORE running those scripts to force creation of a clean rcS.local
#
# the archive includes
#   rcS.local and the packages themselves
# 
# the blindInstall script is run in the background so it can wait for dbus Settings resources
# to become available before running the package install scripts.
#

source "/data/SetupHelper/EssentialResources"
source "/data/SetupHelper/LogHandler"

# wait until dbus settings are active
while [ $(dbus -y | grep -c "com.victronenergy.settings") == 0 ]; do
    logMessage "waiting for dBus settings"
    sleep 1
done

sleep 2


# a package setup script normally prompts for user input
# 'reinstall force' insures SetupHelper is installed without user interaction

if [ -f "/data/SetupHelper/setup" ]; then
	logMessage "blind install SetupHelper"
    # insure package reinstall doesn't get appended to the auto install rcS.local !!!
    rm -f /data/rcS.local
    sync
    /data/SetupHelper/setup reinstall force deferReboot
else
	logMessage "blind install found no SetupHelper setup script - exiting without changes"

fi

